#!/usr/bin/env ansible-playbook
---
- name: Configure Avalanche service
  hosts: avalanche_nodes
  roles:
    - name: golang_base
    - name: avalanche_base
    - name: avalanche_build
    - name: avalanche_user
    - name: avalanche_install
    - name: avalanche_staker
    - name: avalanche_service
